/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

const GlassWall =({...props}) => {
  const { nodes, materials } = useGLTF('/models/glassWall.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={(nodes.Cube as THREE.Mesh).geometry} material={materials.Material} />
    </group>
  )
}

useGLTF.preload('/models/glassWall.glb')
export default GlassWall