/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Issac Ghazanfar (https://sketchfab.com/sheshhh)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/macbook-laptop-7ceb46a1425b475fa7f6bf192e01ed74
Title: MacBook Laptop
*/

import { useGLTF, useVideoTexture } from '@react-three/drei'
import * as THREE from 'three'

const Mac = ({vidPath = '', ...props}) => {
  const { nodes, materials } = useGLTF('/models/mac.glb')
  const vid = useVideoTexture(vidPath);
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.xVreGKoBGSZYMij as THREE.Mesh).geometry}
          material={materials.dKLyhhkbEyMrqky}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.CTBERffHyoCSDBm_0 as THREE.Mesh).geometry}
          material={materials.YjmXmicdBWsFQyD}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.hczGzWOWpedUDYd_0 as THREE.Mesh).geometry}
          material={materials.pEUnNAGXCoAFoUk}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.biHEvGDNnTqamRb as THREE.Mesh).geometry}
          material={materials.dFfswgailNMtaYj}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.TyOrApjEOLhYCaF as THREE.Mesh).geometry}
          material={materials.AZirwHJdxxcChtp}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.vrIckaCELZpnnNK as THREE.Mesh).geometry}
          material={materials.dkOmcmuFedorUKC}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.SadnAkehSlxIwKv as THREE.Mesh).geometry}
          material={materials.VNZklasZKSWjWUk}>
            <meshBasicMaterial map={vid}/>
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.OrhpMXCxeprcNok as THREE.Mesh).geometry}
          material={materials.OfvrpEsWzbOpbcs}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.aLWGnOLpsFWVSfy as THREE.Mesh).geometry}
          material={materials.iFCKstMLETFqCmZ}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.WDUVUVPpNjdIPkb as THREE.Mesh).geometry}
          material={materials.ZPlxrBOYjSNYvVB}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.NqUinIWcwSlXpvt as THREE.Mesh).geometry}
          material={materials.rvYnnyqXrbFJXxh}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.MaufYfIBnxcfRgH as THREE.Mesh).geometry}
          material={materials.SsSIPrCyVNTOxvd}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.aIqeGXayDxWnOWQ as THREE.Mesh).geometry}
          material={materials.EKOOVJzobzfBYEj}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.HrtjMXqDCcINmDE_0 as THREE.Mesh).geometry}
          material={materials.BfIgIOaUEgyoEft}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.zWqVyCKpTAuZNiu_0 as THREE.Mesh).geometry}
          material={materials.zFJMMvikHFjtmzd}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.MYVKQTLmUkzzlBj_0 as THREE.Mesh).geometry}
          material={materials.jIhmcgKbjDOICsY}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.qEJjkxdFZFWJWzR_0 as THREE.Mesh).geometry}
          material={materials.JKvAHnqjqlqshmY}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.lvlCIzdfTmsrnsM as THREE.Mesh).geometry}
          material={materials.iFCKstMLETFqCmZ}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.eeWSraIVipLsSmX_0 as THREE.Mesh).geometry}
          material={materials.JKvAHnqjqlqshmY}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.PgbYkhvRdcmMeGL as THREE.Mesh).geometry}
          material={materials.wOIDWopwzKBeTNU}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.rktWdhtZkCSmqne as THREE.Mesh).geometry}
          material={materials.ZrrjpMZNDbttBCc}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.hztTkkTJBJTZDmk as THREE.Mesh).geometry}
          material={materials.ZrrjpMZNDbttBCc}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.bHBjPHbrqJmhyoR as THREE.Mesh).geometry}
          material={materials.ZrrjpMZNDbttBCc}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.HHcJitDCPTdgnFk as THREE.Mesh).geometry}
          material={materials.RMDHOHZakhhXXHT}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.DRGkWmkJlgmNDJU as THREE.Mesh).geometry}
          material={materials.RMDHOHZakhhXXHT}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.KMwpdMtieDqmHVU as THREE.Mesh).geometry}
          material={materials.RMDHOHZakhhXXHT}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.KgPDMIRPrxAynTV as THREE.Mesh).geometry}
          material={materials.hZBlDyddxAQhuPm}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.XwGJfoaIrduFPcU as THREE.Mesh).geometry}
          material={materials.YjmXmicdBWsFQyD}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.ACMWKGtOCqXifQY as THREE.Mesh).geometry}
          material={materials.RMDHOHZakhhXXHT}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.BkHyotPbPWzwAAj as THREE.Mesh).geometry}
          material={materials.sRPrqogRtliLLae}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.bkcxDtALZjuqGGQ as THREE.Mesh).geometry}
          material={materials.RMDHOHZakhhXXHT}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.ebZHPVwKTmqvgbU as THREE.Mesh).geometry}
          material={materials.kDpbvvjwMgCSCmF}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.uSnVzUkbvcGaVtm as THREE.Mesh).geometry}
          material={materials.AqVxlXuHIFahLKs}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.znOBoeqnOAcWvld as THREE.Mesh).geometry}
          material={materials.dKLyhhkbEyMrqky}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.tIZmzvOOHrlOFci as THREE.Mesh).geometry}
          material={materials.oKQWdLrXUCbYByI}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.UmfOhraHkqkMHJr as THREE.Mesh).geometry}
          material={materials.OFvWomWIIUgmKKA}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.roXkINNmErodbSy as THREE.Mesh).geometry}
          material={materials.oKQWdLrXUCbYByI}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.wWWhLQmmNVhThGV as THREE.Mesh).geometry}
          material={materials.OFvWomWIIUgmKKA}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.JoRHkRchuIHZFdI as THREE.Mesh).geometry}
          material={materials.mEMAJQfiigHeUXV}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.qJLFXXZhlqhKvcM as THREE.Mesh).geometry}
          material={materials.mEMAJQfiigHeUXV}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.thJvyyEdPZIkQGr as THREE.Mesh).geometry}
          material={materials.OFvWomWIIUgmKKA}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.juMIjHdkYweLlGP as THREE.Mesh).geometry}
          material={materials.NzmRSNqyvNKhkmK}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.zNYAavJLMZZchIX as THREE.Mesh).geometry}
          material={materials.ASadxrcBIAXFnLn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.bzbXKgxvWZbXAqu as THREE.Mesh).geometry}
          material={materials.JKvAHnqjqlqshmY}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.guzkNjLPdYYIFbm as THREE.Mesh).geometry}
          material={materials.oINmXIPcNKkHSJV}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.CkZgGMshUOhytMM as THREE.Mesh).geometry}
          material={materials.AvocVUvikCzzMtu}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.oiLbjgjnUUhPosp as THREE.Mesh).geometry}
          material={materials.AvocVUvikCzzMtu}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.nDWhlgWONddUcnN as THREE.Mesh).geometry}
          material={materials.tyKqaDjBmuwfmrZ}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.VAcTKRVsYcEMWxB as THREE.Mesh).geometry}
          material={materials.dkOmcmuFedorUKC}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/mac.glb')
export default Mac;