/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import * as THREE from 'three';

const ShatterBeginning =({...props}) => {
  const { nodes, materials } = useGLTF('/models/shatteredBeg.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Cube001_cell039 as THREE.Mesh).geometry}
        material={materials['Material.001']}
        position={[-4.453, -2.065, -0.005]}
      />
    </group>
  )
}

useGLTF.preload('/models/shatteredBeg.glb')
export default ShatterBeginning;