/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const ShatterBeginning =(props) => {
  const { nodes, materials } = useGLTF('/models/shatteredBeg.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001_cell039.geometry}
        material={materials['Material.001']}
        position={[-4.453, -2.065, -0.005]}
      />
    </group>
  )
}

useGLTF.preload('/models/shatteredBeg.glb')
export default ShatterBeginning;