/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const ShatterMiddle = (props) => {
  const { nodes, materials } = useGLTF('/models/shatteredMid.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001_cell040.geometry}
        material={materials['Material.001']}
        position={[-3.497, 2.527, -0.006]}
      />
    </group>
  )
}

useGLTF.preload('/models/shatteredMid.glb')
export default ShatterMiddle;