/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';
import * as THREE from 'three';

const ShatterMiddle = ({ ...props }) => {
  const { nodes, materials } = useGLTF('/models/shatteredMid.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Cube001_cell040 as THREE.Mesh).geometry}
        material={materials['Material.001']}
        position={[-3.497, 2.527, -0.006]}
      />
    </group>
  );
};

useGLTF.preload('/models/shatteredMid.glb');
export default ShatterMiddle;
